### ISSUE TITLE
Is it possible to provide training weights?

### ISSUE THREAD

**Issue by chovvvvvy** [BITEWKRER/DBNet#1]
Thank you very much for the code, is it possible to provide training weights? If it is possible, it would be appreciated.

**Comment by BITEWKRER** [comment]
Hello, at present, because I have graduated, and the code has no local backup, so I can not provide model training weight, there are other questions please contact me, I try to provide ideas or solutions

**Comment by chovvvvvy** [comment]
Thank you very much for your reply, no more problems for now.
